/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as NotesIdRouteImport } from './routes/notes.$id'
import { Route as ReaderIdRouteImport } from './routes/reader.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderIdRoute = ReaderIdRouteImport.update({
  id: '/reader/$id',
  path: '/reader/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/library': typeof LibraryRoute
  '/stats': typeof StatsRoute
  '/notes/$id': typeof NotesIdRoute
  '/reader/$id': typeof ReaderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/library': typeof LibraryRoute
  '/stats': typeof StatsRoute
  '/notes/$id': typeof NotesIdRoute
  '/reader/$id': typeof ReaderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/library': typeof LibraryRoute
  '/stats': typeof StatsRoute
  '/notes/$id': typeof NotesIdRoute
  '/reader/$id': typeof ReaderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/bookmarks' | '/library' | '/stats' | '/notes/$id' | '/reader/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookmarks' | '/library' | '/stats' | '/notes/$id' | '/reader/$id'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/library'
    | '/stats'
    | '/notes/$id'
    | '/reader/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  LibraryRoute: typeof LibraryRoute
  StatsRoute: typeof StatsRoute
  NotesIdRoute: typeof NotesIdRoute
  ReaderIdRoute: typeof ReaderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$id': {
      id: '/reader/$id'
      path: '/reader/$id'
      fullPath: '/reader/$id'
      preLoaderRoute: typeof ReaderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  LibraryRoute: LibraryRoute,
  StatsRoute: StatsRoute,
  NotesIdRoute: NotesIdRoute,
  ReaderIdRoute: ReaderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
